[build-system]
requires = [
    "wheel",
    "setuptools",
]

[tool.black]
line-length = 80
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | _build
  | build
  | dist
  | doc
)/
| versioneer.py
'''
